name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          export_default_credentials: true

      - name: Re-Build containers on VM instance
        run: |
          echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > temp_ssh_key_file
          echo "${{ secrets.GCE_SSH_PUBLIC_KEY }}" > temp_ssh_key_file.pub
          chmod 0600 temp_ssh_key_file
          gcloud compute ssh --zone "asia-southeast1-b" "doanky8-vm" --project ${{ secrets.GCE_PROJECT }} --ssh-flag="-l huyhoangnguyen147z" --ssh-key-file temp_ssh_key_file --command="echo $(whoami) && ls"
          echo $(whoami) && cd ./.ssh && ls -al
      # - name: Re-Build containers on VM instance
      #   uses: 'google-github-actions/ssh-compute@v0'
      #   with:
      #     instance_name: 'doanky8-vm'
      #     zone: 'asia-southeast1-b'
      #     ssh_private_key: '${{ secrets.GCE_SSH_KEY }}'
      #     command: 'echo Hello'
