name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          export_default_credentials: true

      - name: Generate SSH Key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -C "huyhoangnguyen147z@gmail.com" -f ~/.ssh/id_rsa -N ""

      - name: Display Public Key
        run: cat ~/.ssh/id_rsa.pub

      - name: Re-Build containers on VM instance
        run: |
          gcloud compute ssh --zone "asia-southeast1-b" "doanky8-vm" --project ${{ secrets.GCE_PROJECT }} --ssh-flag="-t" --command="echo $(whoami)"
      # - name: Re-Build containers on VM instance
      #   uses: 'google-github-actions/ssh-compute@v0'
      #   with:
      #     instance_name: 'doanky8-vm'
      #     zone: 'asia-southeast1-b'
      #     ssh_private_key: '${{ secrets.GCE_SSH_KEY }}'
      #     command: 'echo Hello'
          # echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > temp_ssh_key_file
          # echo "${{ secrets.GCE_SSH_PUBLIC_KEY }}" > temp_ssh_key_file.pub
