name: Deploy to Google Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCE_SA_KEY }}
          export_default_credentials: true

      # - name: Re-Build containers on VM instance
      #   run:
      #     gcloud compute ssh --zone "asia-southeast1-b" "ubuntu-gcloud" --project ${{ secrets.GCE_PROJECT }} --ssh-flag="-t" --command="
      #     cd doanky8/app &&
      #     git pull origin master &&
      #     docker-compose -f docker-compose.prod.yml up -d --build"
      - name: Re-Build containers on VM instance
        uses: 'google-github-actions/ssh-compute@v0'
        with:
          instance_name: 'ubuntu-gcloud'
          zone: 'asia-southeast1-b'
          ssh_private_key: '${{ secrets.GCE_SA_KEY }}'
          command: 'cd doanky8/app && git pull origin master && docker-compose -f docker-compose.prod.yml up -d --build'
